spring:
    application:
        name: test_fil_rouge
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test_fil_rouge?currentSchema=public
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: create
